### ISSUE TITLE
precomputed results on YCBV

### ISSUE THREAD

**Issue by Guptajakala** [nv-nguyen/cnos#13]
![001087](https://github.com/nv-nguyen/cnos/assets/40518028/c0ed5513-a910-4df0-9d68-222112b0d239)
This is the result (scene 000048, image 001087) that I parsed from the released precomputed results `sam_pbr_ycbv.json`. Each pixel shows the object ID.
As you can see the "chef can" is under-segmented. There are also many other false positives (the actual objects shouldn't be there). Is this the expected result, or is there anything I'm missing when parsing the json file?

**Comment by Guptajakala** [comment]
![000063_vis](https://github.com/nv-nguyen/cnos/assets/40518028/02ebfc6a-229f-4f9b-9b01-1d3ffd84e3b2)
another example. This looks much worse than what's shown in readme. What's the confidence thres set when getting the `sam_pbr_ycbv.json`?

**Comment by nv-nguyen** [comment]
We use threshold=0.5 for all the visualization as mentioned in the paper. Although some objects are under-segmented, it works well overall for all images of all BOP datasets as reported in the [last BOP challenge](https://cmp.felk.cvut.cz/sixd/workshop_2023/slides/bop_challenge_2023_results.pdf). 

Feel free to re-open the issue if there is any problem with the code!
