### ISSUE TITLE
Why is the paper's reported result different from that in the BOP leaderboard?

### ISSUE THREAD

**Issue by qq456cvb** [nv-nguyen/cnos#18]
Dear author, thanks for open-sourcing the great work. I am confused about the result in the BOP leaderboard (https://bop.felk.cvut.cz/leaderboards/detection-unseen-bop23/core-datasets/). The FastSAM result is different from that in the Table 1. What makes this difference?

**Comment by nv-nguyen** [comment]
The leaderboard that you are mentioning is for detection. In the paper, we reported only the results for segmentation which is [this leaderboard](https://bop.felk.cvut.cz/leaderboards/segmentation-unseen-bop23/core-datasets/)

**Comment by qq456cvb** [comment]
thanks for your reply, my bad, got it!

**Comment by nv-nguyen** [comment]
It happens. Enjoy 😉!
