### ISSUE TITLE
size mismatch for pos_embed

### ISSUE THREAD

**Issue by ccmCCMfk** [nv-nguyen/cnos#19]
Hello, I have a question about when using DINOv2. Could you please help me?I instantiated a vit_small ViT model and tried to load the pretrained weights using the load_pretrained_weights function from utils. Here's the code I wrote:

self.vit_model = vits.__dict__['vit_small'](patch_size=self.patch)
load_pretrained_weights(self.vit_model, 'https://dl.fbaipublicfiles.com/dinov2/dinov2_vits14/dinov2_vits14_pretrain.pth', None)
However, I encountered the following error:
Traceback (most recent call last):
File "/data/PycharmProjects/train.py", line 124, in
model = model(aff_classes=args.num_classes)
File "/data/PycharmProjects/models/locate.py", line 89, in init
load_pretrained_weights(self.vit_model, pretrained_url, None)
File "/data/PycharmProjects/models/dinov2/dinov2/utils/utils.py", line 32, in load_pretrained_weights
msg = model.load_state_dict(state_dict, strict=False)
File "/home/ustc/anaconda3/envs/locate/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DinoVisionTransformer:
size mismatch for pos_embed: copying a param with shape torch.Size([1, 1370, 384]) from checkpoint, the shape in current model is torch.Size([1, 257, 384]).

Could you please help me understand what might be causing this issue? Thank you for your assistance.

**Comment by nv-nguyen** [comment]
`size mismatch for pos_embed: copying a param with shape torch.Size([1, 1370, 384]) from checkpoint, the shape in current model is torch.Size([1, 257, 384]) ` is saying that the model instantiated and the checkpoints are not the same. 

If you want to use small ViT, you can simply change [this line](https://github.com/nv-nguyen/cnos/blob/main/configs/model/descriptor_model/dinov2.yaml#L2) to `dinov2_vits14` or run with override command as I show in the README by adding `model.descriptor_model.model_name=dinov2_vits14 ` to the command that you are running.

Hope it helps and let me know if it is still not working.

**Comment by ccmCCMfk** [comment]
> `size mismatch for pos_embed: copying a param with shape torch.Size([1, 1370, 384]) from checkpoint, the shape in current model is torch.Size([1, 257, 384]) ` is saying that the model instantiated and the checkpoints are not the same.
> 
> If you want to use small ViT, you can simply change [this line](https://github.com/nv-nguyen/cnos/blob/main/configs/model/descriptor_model/dinov2.yaml#L2) to `dinov2_vits14` or run with override command as I show in the README by adding `model.descriptor_model.model_name=dinov2_vits14 ` to the command that you are running.
> 
> Hope it helps and let me know if it is still not working.

I wrote the code from the beginning,and I want to do a new task,this is the code of the network:
class Net(nn.Module):

    def __init__(self, aff_classes=36, backbone = 'dinov2_s',backbones = dino_backbones):
        super(Net, self).__init__()

        self.aff_classes = aff_classes

        self.gap = nn.AdaptiveAvgPool2d(1)
        self.gmp = nn.AdaptiveMaxPool2d(1)

        # --- hyper-parameters --- #
        self.aff_cam_thd = 0.6
        self.part_iou_thd = 0.6
        self.cel_margin = 0.5

        # --- dinov2 features --- #
        self.vit_feat_dim = 384
        self.cluster_num = 1
        self.stride = 14
        self.patch = 14

        # self.vit_model = vits.__dict__['sgformer_s'](patch_size=self.patch, num_classes=0)
        self.vit_model = vits.__dict__['vit_small'](patch_size=self.patch)
        load_pretrained_weights(self.vit_model, f'https://dl.fbaipublicfiles.com/dinov2/dinov2_vits14/dinov2_vits14_pretrain.pth', None)
        # --- learning parameters --- #
        self.aff_proj = Mlp(in_features=self.vit_feat_dim, hidden_features=int(self.vit_feat_dim * 4),
                            act_layer=nn.GELU, drop=0.)
        self.aff_ego_proj = nn.Sequential(
            nn.Conv2d(self.vit_feat_dim, self.vit_feat_dim, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(self.vit_feat_dim),
            nn.ReLU(True),
            nn.Conv2d(self.vit_feat_dim, self.vit_feat_dim, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(self.vit_feat_dim),
            nn.ReLU(True),
        )
        the code was wrote to use dino before，I instantiated a vit_small ViT model and tried to load the pretrained weights using the load_pretrained_weights function from utils.but it turned out a size mismatch error,I don't know the reason why this happen.so I asked you for help.

**Comment by nv-nguyen** [comment]
Can you write a code that I can reproduce the error? I don't see where `vits. __dict__` is defined and I cannot reproduce it.
