### ISSUE TITLE
Poor performance in a object with two colors.

### ISSUE THREAD

**Issue by liuchangji** [nv-nguyen/cnos#21]
First of all, thank you for sharing such an outstanding piece of work. I have an issue here. I have a pair of pliers where you can observe two distinct colors on the upper and lower parts. Consequently, CNOS is only segmenting the yellow section on top. Do you have any suggestions to address this problem? I believe this might be an inherent limitation of the SAM model.

![image](https://github.com/nv-nguyen/cnos/assets/43487003/683373ba-0780-4853-8aae-526ba4bfde6b)

![img_v3_02b5_60e7a8e8-cf1a-43da-8270-8148c7fd166g](https://github.com/nv-nguyen/cnos/assets/43487003/ac03fde7-4daa-460f-9fb9-b921dc157a31)

**Comment by qidihan** [comment]
Hi, did you solve this problem? I'm having the same issues. It seems the problem of SAM model, I tried to change the stability and iou score on SAM model, still didn't fix this problem.
