### ISSUE TITLE
release pre-computed Linemod and YCBV results

### ISSUE THREAD

**Issue by Guptajakala** [nv-nguyen/cnos#3]
Is there any plan to release the pre-computed Linemod and YCBV segmentation results? People who are interested in evaluating benchmarks might want to directly use your segmentation w/o needing to setup the code and re-run themselves.

**Comment by nv-nguyen** [comment]
Yes, it was released [here](https://github.com/nv-nguyen/cnos#testing-on-bop-datasets-rocket) from the initial commit.
