### ISSUE TITLE
DINOv2 for image feature extraction

### ISSUE THREAD

**Issue by JIaqiYang78** [nv-nguyen/cnos#8]
Hello, I have a question. I didn't find the reference of 'src->model->dinov2.py'. So, in which file did you import dinov2 model? Haven't you provided the training file?

**Comment by nv-nguyen** [comment]
This work uses hydra and the `src.model.dinov2.py` was imported through this [config](https://github.com/nv-nguyen/cnos/blob/main/configs/model/descriptor_model/dinov2.yaml#L1) and [this line](https://github.com/nv-nguyen/cnos/blob/main/run_inference.py#L42) in run_inference.py. If you run exactly the same commands in README, it should work.

**Comment by JIaqiYang78** [comment]
> This work uses hydra and the `src.model.dinov2.py` was imported through this [config](https://github.com/nv-nguyen/cnos/blob/main/configs/model/descriptor_model/dinov2.yaml#L1) and [this line](https://github.com/nv-nguyen/cnos/blob/main/run_inference.py#L42) in run_inference.py. If you run exactly the same commands in README, it should work.

Ok, cool, I found it, thanks.
